### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by fatihkizmaz** [thecodrr/vspeech#1]
Followed all manual steps and successfully compiled a sample program.
But when i run program it prints "Illegal instruction (core dumped)"
Did i miss any step?

Using OS: Ubuntu 18.04.3

**Comment by thecodrr** [comment]
Can you run the program in the `vspeech/cmd` folder? And can you upload the wav file you used so I can test with it?

Would appreciate if you show some code.

**Comment by fatihkizmaz** [comment]
![image](https://user-images.githubusercontent.com/17065192/72440773-8a2ef780-37ba-11ea-98c1-f6499b15f4e7.png)

Tried with your cmd example.  No line changed.
Program compiles succesfully. 
But when it starts it prints "Illegal instruction (core dumped)"
It never asks for os args. 

But i can compile and run a hello world app with V. I think error is not related to V.

I extracted "native_client.amd64.cpu.linux.tar.xz" to lib folder. Should i use a different binary? It sounds like this error is caused by deepspeech binary for me.

**Comment by thecodrr** [comment]
Can you try running this command:
`export LD_LIBRARY_PATH=$PWD/lib/`
and then `v run .`

You should also try a different binary. This seems to be an issue with DeepSpeech.

My `lib/` folder looks like this:
![image](https://user-images.githubusercontent.com/7473959/72456350-55389a00-37e6-11ea-89c0-70890b595f07.png)

**Comment by fatihkizmaz** [comment]
I learned that my CPU does not support some instructions (eg: AVX) which is used at deepspeech native client binaries.
So i need to buil native client myself described here: https://github.com/mozilla/DeepSpeech/tree/master/native_client
Otherwise i should use built binaries with a modern cpu.
